spring:
  h2.console:
    enabled: true
    path: '/db-h2'
  datasource:
    url: 'jdbc:h2:file:./todoDB'
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: '*'